version: '3'

services:
  #
  # Front 1
  #
  front-1:
    restart: unless-stopped
    build:
      context: ./configs/front-1
      dockerfile: ./Dockerfile
    image: prytoegrian/front-1
    container_name: front-1
    expose:
        - 8080
        - 80
    networks:
     - frontend

  #
  # Front 2
  #
  front-2:
    restart: unless-stopped
    build:
      context: ./configs/front-2
      dockerfile: ./Dockerfile
    image: prytoegrian/front-2
    container_name: front-2
    expose:
        - 8080
        - 80
    networks:
     - frontend


  #
  # Load balancer
  #
  load-balancer:
    restart: unless-stopped
    build:
      context: ./configs/load-balancer
      dockerfile: ./Dockerfile
    image: prytoegrian/load-balancer
    container_name: load-balancer
    ports:
      - 80:80
    networks:
     - frontend
    cap_add:
        - NET_ADMIN

networks:
  frontend:
